Defensive coding fix
The `$matches` array returned by `explode()` can be an empty array. In that case, `end()` would return `false`, which due to the string cast would become an empty string.

Psalm flags the string cast though with:
```
ERROR: RedundantCast - src/Fqsen.php:66:21 - Redundant cast to string (see https://psalm.dev/262)
            $name = (string) end($matches);
```
... which in my opinion is incorrect.

I tried various options to get round this, but most ended up being flagged by Psalm again, even though IMO this flagging is incorrect.

Either way, the current change fixes the Psalm violation and does not trigger new violation flags.